global:
  user: curve
  ssh_port: 22
  private_key_file: /home/curve/.ssh/id_rsa

hosts:
  - host: server-host1
    hostIp: 10.0.1.1
    labels:
      - automount
    envs:
      - SUDO_ALIAS=sudo
      - OPTIONS=""
  - host: server-host2
    hostIp: 10.0.1.2
    labels:
      - automount
    envs:
      - SUDO_ALIAS=sudo
      - OPTIONS=""