container_image: opencurvedocker/curvefs:latest
mdsOpt.rpcRetryOpt.addrs: 10.0.1.1:6700,10.0.1.2:6700,10.0.1.3:6700
log_dir: /home/curve/curvefs/logs/client

### if fstype is s3
s3.ak: <>
s3.sk: <>
s3.endpoint: nos-eastchina1.126.net
s3.bucket_name: curvefs

### if fstype is volume
# curvebs cluster's mds ip and port
curvebs.cluster: 10.0.10.1:6700,10.0.10.2:6700,10.0.10.3:6700
# volume size in bytes
volumeSize: 10737418240
# volume name
volumeName: /volume
# user of volume
volumeUser: user
# password of volume
# if not specified when create volume then leave it empty string ''
volumePassword: password
