user: curve
ssh_port: 22
private_key_file: /home/curve/.ssh/publish_rsa
vevsion: 1.2.0
host:
  - 10.0.1.1
  - 10.0.1.2
  - 10.0.1.3
disk:
  - /dev/sda:/data/chunkserver0:90  # device:mount_path:usage_percent
  - /dev/sdb:/data/chunkserver1:90
  - /dev/sdc:/data/chunkserver2:90
