# node_exporter will deploy on all servers of cluster by default
node_exporter:
  container_image: prom/node-exporter:latest
  listen_port: 9100

# this container provide monitor dashboard, use cluster iamge if not set
container_image: opencurvedocker/curvebs:v1.2.6

host: server-host

prometheus:
  container_image: prom/prometheus:latest
  data_dir: /tmp/monitor/prometheus
  listen_port: 9090
  retention.time: 7d
  retention.size: 256GB

grafana:
  container_image: grafana/grafana:latest
  data_dir: /tmp/monitor/grafana
  listen_port: 3000
  username: admin
  password: curve
  