kind: curvebs
global:
  container_image: opencurvedocker/curvebs:v1.2.7-rc1_0ff8409
  log_dir: ${home}/logs/${service_role}${service_host_sequence}
  data_dir: ${home}/data/${service_role}${service_host_sequence}
  s3.nos_address: <>
  s3.snapshot_bucket_name: <>
  s3.ak: <>
  s3.sk: <>
  variable:
    home: /tmp
    target: server-host

etcd_services:
  config:
    listen.ip: ${service_host}
    listen.port: 2380${service_host_sequence}
    listen.client_port: 2379${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

mds_services:
  config:
    listen.ip: ${service_host}
    listen.port: 670${service_host_sequence}
    listen.dummy_port: 770${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

chunkserver_services:
  config:
    listen.ip: ${service_host}
    listen.port: 820${service_host_sequence}  # 8200,8201,8202
    data_dir: /data/chunkserver${service_host_sequence}  # /data/chunkserver0, /data/chunksever1
    copysets: 100
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}

snapshotclone_services:
  config:
    listen.ip: ${service_host}
    listen.port: 555${service_host_sequence}
    listen.dummy_port: 810${service_host_sequence}
    listen.proxy_port: 800${service_host_sequence}
  deploy:
    - host: ${target}
    - host: ${target}
    - host: ${target}