name: CI

on:
  push:
    branches:
      - master
      - develop
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  GO_VERSION: 1.18

jobs:

  verify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Verify Code
        run: make verify

  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint golang code
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          args: --timeout 10m -v
          skip-cache: true
